require('custom.config.keymaps')
require('custom.config.options')
require('custom.config.pluginconfigs')
require('custom.config.LSP-config')
require('custom.config.treesitter-config')
require('custom.config.nvim-cmp-config')
